# Generated by Django 5.0.4 on 2024-04-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
