# Generated by Django 5.0.4 on 2024-04-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.CharField(help_text='Enter the address of the store.', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.IntegerField(default=0, help_text='Enter a unique ID for the store.', unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(help_text='Enter the name of the store.', max_length=100),
        ),
    ]
