# Generated by Django 5.0.4 on 2024-05-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
