# Generated by Django 5.0.4 on 2024-05-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
    ]
